- block:
  - name: Gather package facts
    package_facts:
      manager: apt

  - name: download install script
    get_url:
      url: https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh
      dest: /tmp/
      mode: 0777
    when: '"git-lfs" not in ansible_facts.packages'

  - name: execute install script
    command: bash /tmp/script.deb.sh
    when: '"git-lfs" not in ansible_facts.packages'

  - name: remove install script
    file:
      path: /tmp/script.deb.sh
      state: absent
    when: '"git-lfs" not in ansible_facts.packages'

  - name: install git-lfs
    apt:
      name: git-lfs
      update_cache: yes
      install_recommends: no

  tags:
    - git-lfs
