version: "2.3"
services:
  ubuntu:
    image: ubuntu-provisioning
    network_mode: "bridge"
    volumes:
      - $PWD:/work
    environment:
      - ANSIBLE_PLAYBOOK_OPTIONS=--
    build:
      context: .
    command: bash -c """
      ansible-galaxy install -r requirements.yml &&
      ansible-playbook sites/ubuntu-gpu.yml
      """
