---
- block:
  - name: Clone repository
    git:
      repo: "{{ dotfiles_repo }}"
      dest: "{{ dotfiles_repo_local_destination }}"
      version: "{{ dotfiles_repo_version }}"

  - name: Make
    make:
      chdir: "{{ dotfiles_repo_local_destination }}"

  - include_tasks: setup-zsh.yml
    when: dotfiles_setup_zsh

  - include_tasks: setup-vim.yml
    when: dotfiles_setup_vim
