---
packages:
  - alfred
  - atom
  - bettertouchtool
  - docker
  - evernote
  - font-source-code-pro
  - font-source-code-pro-for-powerline
  - google-backup-and-sync
  - google-japanese-ime
  - hyper
  - Karabiner-Elements
  - iterm2
  - xquartz
