---
- block:
  - name: Ensure MAS is installed.
    homebrew: name=mas state=present

  - name: Get MAS account status
    command: mas account
    register: mas_account_result
    failed_when: mas_account_result.rc > 1
    changed_when: false

  - name: List installed MAS apps.
    command: mas list
    register: mas_list
    check_mode: no
    changed_when: false

  - name: Ensure configured MAS apps are installed.
    command: mas install "{{ item.id|default(item) }}"
    with_items: "{{ apps }}"
    when: (item.id | default(item) | string) not in mas_list.stdout

  - name: Upgrade all apps (if configured).
    command: mas upgrade
    when: mas_upgrade_all_apps

  tags:
    - mas
