- block:
  - name: homebrew update
    homebrew:
      update_homebrew: true
      upgrade_all: no

  - name: homebrew packages install
    homebrew:
      name: "{{ packages }}"
      state: "present"

  tags:
    - homebrew
