---
- hosts: localhost
  connection: local
  gather_facts: yes
  roles:
    - role: osx_defaults

    - role: homebrew
      packages:
        - ansible
        - direnv
        - git-lfs
        - htop
        - mas
        - nvim
        - svn
        - tig
        - tmux
        - wget
        - zsh

    - role: homebrew_cask
      packages:
        - alfred
        - appcleaner
        - atom
        - bettertouchtool
        - docker
        - font-source-code-pro
        - font-source-code-pro-for-powerline
        - google-backup-and-sync
        - google-japanese-ime
        - hyper
        - Karabiner-Elements
        - iterm2
        - visual-studio-code
        - xquartz

    - role: mas
      apps:
        - name: Keynote
          id: 409183694
        - name: Pages
          id: 409201541
        - name: Numbers
          id: 409203825
        - name: Xcode
          id: 497799835
        - name: Amphetamine
          id: 937984704
        - name: Kindle
          id: 405399194
        - name: Magnet
          id: 441258766
        - name: WiFi Explorer
          id: 494803304
        - name: Slack
          id: 803453959
        - name: Trello
          id: 1278508951
        - name: Bitwarden
          id: 1352778147
