---
- hosts: localhost
  connection: local
  roles:
    - role: apt
      become: yes

    - role: git-lfs
      become: yes

    - role: vim
      become: yes

    - role: gantsign.bat
      become: yes

    - role: geerlingguy.docker
      docker_users: ["{{ ansible_user_id }}"]
      become: yes

    # Find nvidia driver version below:
    # https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/
    # https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-major-component-versions
    - role: nvidia.nvidia_driver
      nvidia_driver_ubuntu_install_from_cuda_repo: yes
      nvidia_driver_ubuntu_cuda_packages: ["cuda-drivers"]
      nvidia_driver_package_version: "440.118.02-1"  # CUDA 10.2
      nvidia_driver_skip_reboot: yes
      become: yes

    - role: nvidia-docker
      nvidia_docker_version: 2.6.0
      become: yes
